name: jam_re_store

description: A recycling app.

publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: ">=2.15.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0  

  introduction_screen: ^2.1.0

  provider: ^6.0.0

  cupertino_icons: ^1.0.2
  
  flutter_hooks: ^0.18.2+1

  dio: ^4.0.4

  flutter_bloc: ^8.0.1

  equatable: ^2.0.3

  lottie: ^1.2.2
  
  intl_phone_number_input: ^0.7.0+2

  google_fonts: ^2.3.1
  
  dartz: ^0.10.1

  flutter_secure_storage: ^5.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

  uses-material-design: true

  generate: true

  assets:
    - assets/